### PR TITLE
Final delivery for the Cryosphere Virtual Laboratory

### PR DESCRIPTION
**Pull request by cl3mens22**

### CODE REVIEW

**Comment by ykern** [comment]
Thank you very much for the pull request. We would like to check the content of your notebook against your project proposal. For this we need explanation of the aims and results and background information.

Please update the notebook and 
- add sections explaining the notebook goals
- provide information about the code cell intentions
- explain the results to the general audience

You can find an example on how to format documentation in the [cvl_get-started.ipynb](https://github.com/CryosphereVirtualLab/public-notebooks/blob/main/cvl_get-started.ipynb) notebook.

**Comment by cl3mens22** [comment]
Thanks for the input, I will implement the feedback and make a new pull request with the updated version.

**Comment by ykern** [comment]
Hei, there is no need to close the pull request. You can simply add new commits to your branch [cl3mens22:'disturbed_lake_data'](https://github.com/cl3mens22/public-notebooks/tree/'disturbed_lake_data'). This will automatically update the this pull request with the changes.

**Comment by cl3mens22** [comment]
Sorry for deleting the head repository, had problems with the different branches and updating this existing one... Had no other idea how to do it... first time on github... sorry about that.

**Comment by ykern** [comment]
No worries. Can be a bit confusing in the beginning, but we are here to help you :-) I see you opened a new pull request, so all fine.

**Pull request closed without merging**
