### PR TITLE
CF convention NetCDF exporter

### PR DESCRIPTION
**Pull request by RolfOleJenssen**
__IMPORTANT:__ _Check that none of your commits has hard-coded credentials (user, password)! Otherwise, don't open a pull request and get in touch with us first._

_INFO: The checklist below will be edited by the CVL team. If you want to add any description use the place holder in the end.
To update the pull request just commit to the related branch. There is no need to delete the pull request and reopen a new one._
# CVL submission criteria

## Structure
- [x] Introduction
- [x] Load data
- [x] Process data
- [x] Result visualisation
- [x] Summary of notebook outcomes

## Content requirements
- Self-contained
  - [x] Runs successfully
  - [x] Reproducible
- [x] Sufficient inline (markdown) documentation
- [x] In accordance with project description
- [x] Utilisation of CVL data catalogue (if applicable, alternative portals such as Zenodo could be utilised as well)

---
# Description of pull request
_(Relates to previous comments on #15 )_

### CODE REVIEW

**Comment by RolfOleJenssen** [comment]
Thank you for the feedback!
Changes made with previous pull request comments in mind. 
I had some strange issues with getting the IOOS compliance-checker suite working within python, so for now, the general implementation is there but commented out and instead is checked using a terminal command from python.

I uploaded the test dataset to zenodo and provided the link in the markdown for " Load dataset". 
This could of course be implemented directly in python using Zenodopy, but generally, this cell is to be edited by the user to import whatever dataset they want to use. 

I have indicated more clearly what cells need user input. 

Regarding publishing the netCDF's: I'm thinking this notebook is more for testing if the netCDF generation works. The actual publishing has at least in my experience been with scp to a data center host, and could with benefit be kept as a separate operation.

**Comment by ykern** [comment]
I opened a pull request with some fixes and suggestions
- https://github.com/RolfOleJenssen/public-notebooks/pull/1
  - After installing `compliance-checker` via `conda-forge` as provided in the added `provision.sh` file, everything runs as expected. 
  - I implemented the Zenodo/doi download as a minimum, so that no data files are required in the repo itself.
  - see other changes there

The reason for our suggestions in https://github.com/CryosphereVirtualLab/public-notebooks/pull/15#issuecomment-1411668874 were to round up this notebook into an overall example of how a FAIR dataset could be produced. That doesn't mean that Zenodo has to be used. We just thought it could have been a good example to showcase a complete processing chain.

Anyway. If you are happy with my pull request and when you have accepted, I am fine with merging this pull request into the main repo.

**Comment by RolfOleJenssen** [comment]
Thank you for the suggestions and fixes. I have accepted the pull request.

**Comment by ykern** [comment]
Thanks :+1:  I will merge this into the main repo now.

**Pull request merged**
