### PR TITLE
Sentinel-1 imagery time series generation

### LINKED ISSUE #35: S2 data access
I am using the sentinelAPI to search for overlapping S1 and S2 data, then I use the S2 name strings to stitch together the url and access the data with xarray as shown in the example notebook.

For a test case, I get 6 hits for S2 imagery:
S2A_MSIL1C_20220401T151811_N0400_R068_T29XMH_20220401T173711
S2A_MSIL1C_20220401T151811_N0400_R068_T28XEP_20220401T173711
S2A_MSIL1C_20220401T151811_N0400_R068_T29XMJ_20220401T173711
S2B_MSIL1C_20220401T142739_N0400_R139_T29XMH_20220401T165128
S2B_MSIL1C_20220401T142739_N0400_R139_T28XEP_20220401T165128
S2B_MSIL1C_20220401T142739_N0400_R139_T29XMJ_20220401T165128

From these I build the following urls:
https://nbstds.met.no/thredds/dodsC/NBS/S2A/2022/04/01/S2A_MSIL1C_20220401T151811_N0400_R068_T29XMH_20220401T173711.nc
https://nbstds.met.no/thredds/dodsC/NBS/S2A/2022/04/01/S2A_MSIL1C_20220401T151811_N0400_R068_T28XEP_20220401T173711.nc
https://nbstds.met.no/thredds/dodsC/NBS/S2A/2022/04/01/S2A_MSIL1C_20220401T151811_N0400_R068_T29XMJ_20220401T173711.nc
https://nbstds.met.no/thredds/dodsC/NBS/S2B/2022/04/01/S2B_MSIL1C_20220401T142739_N0400_R139_T29XMH_20220401T165128.nc
https://nbstds.met.no/thredds/dodsC/NBS/S2B/2022/04/01/S2B_MSIL1C_20220401T142739_N0400_R139_T28XEP_20220401T165128.nc
https://nbstds.met.no/thredds/dodsC/NBS/S2B/2022/04/01/S2B_MSIL1C_20220401T142739_N0400_R139_T29XMJ_20220401T165128.nc

I try to access the data using xr.open_dataset(url). This works for images 2, 3, 5, and 6 from the above list, but fails for 1, and 4 (netCDF file not found). Any idea what I am doing wrong?

### PR DESCRIPTION
**Pull request by jlo031**
__IMPORTANT:__ _Check that none of your commits has hard-coded credentials (user, password)! Otherwise, don't open a pull request and get in touch with us first._

_INFO: The checklist below will be edited by the CVL team. If you want to add any description use the place holder in the end.
To update the pull request just commit to the related branch. There is no need to delete the pull request and reopen a new one._
# CVL submission criteria

## Structure
- [x] Introduction
- [x] Load data
- [x] Process data
- [x] Result visualisation
- [x] Summary of notebook outcomes

## Content requirements
- Self-contained
  - [x] Runs successfully
  - [x] Reproducible
- [x] Sufficient inline (markdown) documentation
- [x] In accordance with project description
- [x] Utilisation of CVL data catalogue (if applicable, alternative portals such as Zenodo could be utilised as well)

---
# Description of pull request
Making a new pull request so you can start looking at the notebook as it is getting closer to its final version. I'll still work on more visualization, potential S2 overlap, and looping over all hits in the sentinelAPI.query to generate a time series of results.

### CODE REVIEW

**Comment by ykern** [comment]
Nice work! While I am looking at #35 and already diving into your files I will just start adding feedback here already. 
- You can add a local `.gitignore` file into your subdirectory that already includes your recommended exclusion of the `.env` file. Git will follow both, the `.gitignore` in your subdirectory and the one at parent level

**Comment by ykern** [comment]
Amazing and very valuable work :+1: Everything runs fine and documentation looks very good and understandable. Good job!

Only two very minor comments:
1) Can you run the following command in terminal (while rooted at the top level of the repo) to recover the changed `provision.sh` file in main directory
```
git checkout 78d7f4384e3e8c0ac581599046bb2de11f705f7b -- provision.sh
```
and then commit again to the pull request? I see you have the same project specific provision file in your directory anyway. So this would just restore the general provision file.

2) Can I suggest to add just some minimal info to the README file? Just a project title and a short description. Can be the copy from the Introduction of the notebook. Don't want you to spend more time it, just so that the Readme is not empty :-)

**Comment by jlo031** [comment]
Thank you. I'll fix the provision.sh in the main directory and add some info to the README as soon as I have a minute. Will let you know when I am done.

**Comment by jlo031** [comment]
Done. Should be finished now, but just let me know if anything else is missing :)

**Comment by ykern** [comment]
Looks very good! Thanks for the great work and constructive feedback!

**Pull request merged**
