### PR TITLE
Temprature effect on ice core

### PR DESCRIPTION
**Pull request by Faramarz-bagherzadeh**
__IMPORTANT:__ _Check that none of your commits has hard-coded credentials (user, password)! Otherwise, don't open a pull request and get in touch with us first._

_INFO: The checklist below will be edited by the CVL team. If you want to add any description use the place holder in the end.
To update the pull request just commit to the related branch. There is no need to delete the pull request and reopen a new one._
# CVL submission criteria

## Structure
- [x] Introduction
- [x] Load data
- [x] Process data
- [x] Result visualisation
- [x] Summary of notebook outcomes

## Content requirements
- Self-contained
  - [x] Runs successfully
  - [x] Reproducible
- [x] Sufficient inline (markdown) documentation
- [x] In accordance with project description
- [x] Utilisation of CVL data catalogue (if applicable, alternative portals such as Zenodo could be utilised as well)

---
# Description of pull request
_(Relates to previous comments on #21)_
Hello,

I edited the previous version as requested and added the final version in a separate folder.

Best Regards
Faramarz

### CODE REVIEW

**Comment by ykern** [comment]
Good job and very good improvements!
There are a few things to follow up on, see below.

## Project description
According to your project description you aimed to investigate the relations between surface parameters and ice/firn microstructure (grain growth, air cavities, firn layering). As none experts in this field we have one question to clarify if we understand the intentions of your project correctly:
- It looks like you focussed on density of the ice in relation to the temperature measured remote, is that correct? 
Is there a reason why you did not look into any other parameters (like mentioned in your project description) or was it the intention from the start to compare temperature and density?

Edit (7.2.23): The intention of this question is just to figure out if the reasons of this approach are scientific or because of the CVL framework is missing features that you would have needed. No detailed explanation necessary :-)

## Structure
Here a few minor suggestions for further improvements:
* Update labels (with units if applicable) for plots in 
  * step 3: 
    * [ ] use names instead of `x` and `y`
  * step 4: 
    * histogram: 
      * [ ] units
      * [ ] is the y-axis label correct?
      * [ ] add legend or a way to indicate what the different lines/histograms represent
    * last plot: 
      * [ ] units
      * [ ] is the x-axis label correct or should it be `hours`?
      * [ ] add legend for different colours, maybe second y-axis for temperature scale missing or what are the two different lines?
* the conclusion contains the scientific outcomes. Can you also add a short summary of what has been achieved from a technical point of view in this notebook?

## Technical
### Missing dependency
The notebook requires a new dependency to be installed, please update your `environment.yaml` file with the following content
```yaml
name: env
channels:
  - conda-forge
dependencies:
  - earthaccess=0.4.*
```

### Notebook execution
I can't run the whole notebook yet. In cell 8 
```python
#downloading the selected granules in local path
earthaccess.download(daily_granules, local_path="./modis_data")
```
  I get a long list of errors in the type of:
```bash
Error while downloading the file MODGRNLD.2011129.daily.v01.1.nc
Traceback (most recent call last):
  File "/opt/conda/lib/python3.10/site-packages/earthaccess/store.py", line 498, in _download_file
    r.raise_for_status()
  File "/opt/conda/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 503 Server Error: Service Unavailable for url: https://n5eil01u.ecs.nsidc.org/DP2/MOST/MODGRNLD.001/2011.05.09/MODGRNLD.2011129.daily.v01.1.nc

Error while downloading the file MODGRNLD.2011131.daily.v01.1.nc
Traceback (most recent call last):
  File "/opt/conda/lib/python3.10/site-packages/earthaccess/store.py", line 498, in _download_file
    r.raise_for_status()
  File "/opt/conda/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 503 Server Error: Service Unavailable for url: https://n5eil01u.ecs.nsidc.org/DP2/MOST/MODGRNLD.001/2011.05.11/MODGRNLD.2011131.daily.v01.1.nc

[...]
```
Do you experience something similar?

**Comment by Faramarz-bagherzadeh** [comment]
Thank you for your comment, please find the answer as follows:
**Project description**
In the beginning, I was not sure how far I could go in this project, therefore I wrote a bigger goal. As you mentioned correctly, here I only used ice core density and satellite temperature data because of the following reasons:

1. Very limited time, especially having issue#13 with downloading the data.
2. Lack of ice core data, and I could not get permission to use my own data from AWI.
3. Lack of on-site data, in places where ice cores were collected in CVL data.

Despite the given problems, I could obtain the most practical, and relevant parameters of the ice cores and climate data (temperature).


**Structure**
All the corrections are done, Please have a look and let me know if it looks good.

**Missing dependency**
It is added now

Conclusion is modified 

**Notebook execution**
It was running. Now I also have these errors, and only around 100 files get downloaded. I have no idea what is happening.



'''

**Comment by ykern** [comment]
Great work! :+1: 
Thanks for the additional explanations.

### Notebook execution
I opened a pull request to your branch `figures_updated` suggesting some small changes on your notebook. 
- slightly updated the login procedure according to [this sample notebook](https://github.com/nsidc/earthaccess/blob/main/notebooks/EarthdataLogin.ipynb)
- changed the way of downloading the files by reducing the used threads from default 8 down to 1 according to [this issue](https://github.com/nsidc/earthaccess/issues/96)

After those changes I ran the notebook with a small subset of data (by changing the date range to only 1 month). Then it ran fine.
Please have a look and you might want to try and run the whole notebook now with those changes. If you are happy with my suggestions, can you 
1) merge the pull request (https://github.com/Faramarz-bagherzadeh/public-notebooks/pull/1) I opened into your repo?
2) then merge your branch [`figures_udpated`](https://github.com/Faramarz-bagherzadeh/public-notebooks/tree/figures_updated) into your own [`main`](https://github.com/Faramarz-bagherzadeh/public-notebooks/tree/main) branch?

Right now you have two pull requests open (#32 and #38) for each of the brands. If you follow the steps above, everything will be added to this pull request #32  here.

**Comment by ykern** [comment]
Thank you, nice work :+1:  I will merge this now and
- close #38 
- close https://github.com/Faramarz-bagherzadeh/public-notebooks/pull/1

**Pull request merged**
