### PR TITLE
netCDF creator

### PR DESCRIPTION
**Pull request by RolfOleJenssen**
__IMPORTANT:__ _Check that none of your commits has hard-coded credentials (user, password)! Otherwise, don't open a pull request and get in touch with us first._

_INFO: The checklist below will be edited by the CVL team. If you want to add any description use the place holder in the end.
To update the pull request just commit to the related branch. There is no need to delete the pull request and reopen a new one._
# CVL submission criteria

## GitHub
- [x] Pull request sent
- [ ] Merged

## Structure
- [x] Introduction
- [x] Load data
- [x] Process data
- [x] Result visualisation
- [ ] Summary of notebook outcomes

## Content requirements
- Self-contained
  - [ ] Runs successfully
  - [ ] Reproducible
- [ ] Sufficient inline (markdown) documentation
- [ ] In accordance with project description
- [ ] Utilisation of CVL data catalogue (if applicable, alternative portals such as Zenodo could be utilised as well)

---
# Description of pull request
Hi, 
This is my proposed framework to export transect UAV data and associated meta-data from Jupyter
environment variables to netCDF in accordance with CF metadata conventions.
This is to work as a detailed example for users who want to submit non-mesh datasets while following the CF conventions and best practices.

I have included a test dataset that is a little large (approx. 60 Mb) in a tmp folder. 

Feel free to give feedback on this. 

cheers,

Rolf

### CODE REVIEW

**Comment by ykern** [comment]
Thank you very much for the pull request. This is a nice illustration how a NetCDF file can be created from a xyz time series. However, the script basically explains how to use the NetCDF4 package and is not necessarily a framework that may be reused by other users by for example importing as a library. To make it useful for the CVL project, we would suggest turning it into a library package that could be installed in the CVL environment and that has an API.

**Comment by RolfOleJenssen** [comment]
Thank you for the feedback.
I’m unsure if a library is the way to go with this project. ?
The goal of the notebook is to clarify some of the ambiguities with netCDF file generation. Especially what metadata is important/relevant and what metadata is provided by the host. Some “best practices” on number formatting are also there but not explained in detail. I gathered this info from a data center admin at MET. 
I found that a notebook is the best format since the gathered information combines CF conventions and “best practices” I got from MET, and should still be read and understood by the user.
Perhaps the notebook could be explained better and in more detail?

**Comment by ykern** [comment]
In general, the more detailed the explanation the better it will be to understand for a user not familiar to the subject. So if you think that there could be more explanation added that would be great.

To turn the project into a library was only an idea on how the project could be packaged in another way. However, we of course leave that decision to you. 
If you want to keep the notebook structure we would like to suggest to add a few more steps. As you describe in your project you want to create a dataset that complies with the FAIR convention. Below some suggestions on what we would like to suggest to add to ensure that the result is FAIR.

__Findable__
Currently, the example dataset is located in the repo. We would suggest to publish it so it can be loaded from an external address. For example [Zenodo](https://zenodo.org/) could be a place to check out for this. There you could add some metadata and it will get a doi which can then be imported in the notebook. 

__Resuable__
In order to make the created NetCDF reusable, it would be good to evaluate the result and check it against the CF conventions. Any of the following could be used:
- [IOOS compliance-checker suite](https://github.com/ioos/compliance-checker): has python implementation and something I am using myself. It creates a report in the end of how well a NetCDF complies with a selected convention.
- [cfchecker](https://pypi.org/project/cfchecker/)
- [yanc](https://github.com/metno/yanc)

In addition, we would suggest a programmatic way of publishing the created dataset. In your case that could be to append it to the already existing example dataset entry on Zenodo or create a new one. Not sure of the exact syntax and procedure here but the following links should provide you with info about this:
- https://developers.zenodo.org/
- https://pypi.org/project/zenodo-client/

__Further suggestions__
- [ ] indicate more clear where a user of your notebook would need to edit input if they would like to adjust it to their dataset, that they want to convert into a NetCDF
- [ ] the __Read netCDF file__ section seems to check if the NetCDF file created looks fine. Maybe you could find a more fitting title for that section because the file is not only read but also visualised and potentially checked against conventions (see compliance checker feedback above)

**Comment by ykern** [comment]
Continued in #36

**Pull request closed without merging**
