### PR TITLE
Ecosystem data for selected disturbed lakes in permafrost regions

### PR DESCRIPTION
**Pull request by cl3mens22**
__IMPORTANT:__ _Check that none of your commits has hard-coded credentials (user, password)! Otherwise, don't open a pull request and get in touch with us first._

_INFO: The checklist below will be edited by the CVL team. If you want to add any description use the place holder in the end.
To update the pull request just commit to the related branch. There is no need to delete the pull request and reopen a new one._
# CVL submission criteria

## Structure
- [x] Introduction
- [x] Load data
- [x] Process data
- [x] Result visualisation
- [x] Summary of notebook outcomes

## Content requirements
- Self-contained
  - [x] Runs successfully
  - [x] Reproducible
- [x] Sufficient inline (markdown) documentation
- [x] In accordance with project description
- [x] Utilisation of CVL data catalogue (if applicable, alternative portals such as Zenodo could be utilised as well)

---
# Description of pull request
(Relates to previous PR #26 )

### CODE REVIEW

**Comment by ykern** [comment]
Amazing and very extensive work! Well done :+1: 
I opened a pull request with some updates that I added while going through your notebook. 
- see https://github.com/cl3mens22/public-notebooks/pull/1

Some of those changes were necessary to run the notebook. I was able to run almost everything. The only code that always crashed the kernel was the era5 cutting loop that has the `decision` bool. I rewrote it slightly to increase the speed by swapping the `for` loops around and reduce the amount of time calling `grps.select()`. But I still don't manage to run it completely. Though, I assume it is working with more CPU power, so I don't see a reason to change anything else here. Users can decide for themselves if they want to try or not. Did it run all well for you?

Have a look at the suggested changes and accept the pull request if you are happy with them. Then this pull request here will automatically be updated and we are ready to merge!
Good job :-)

**Comment by ykern** [comment]
Just to follow this up. We got an answer from PTEP how to implement the web service there and access from local browser. This is after the project now, so I don't expect you to implement any of this into your notebook. I just want to add it here for reference and future development if of interest:

```
The followings are needed in order to connect to a server running in a jupyter notebook:

    A PTEP dev. VM at https://www.polartep.io/ssoportal/pages/p_devTest.jsf
    The server software running in a jupyter notebook at www.polartep.io/jupyter
    A reverse port forwarding ssh tunnel between the dev. VM and the notebook
    VPN connection between the user's PC and PTEP net.


Instructions

VM preparation:

    Create a PTEP dev VM if you don't have one already.
    Identify its IP address. (will be referenced as <PTEP-VM-IP> in this doc.)
    Login via SSH
    Gain root access:
        execute: sudo su
    Configure the SSH service so that it accepts bind address configuration from remote client:
        execute: sed -i 's/#GatewayPorts.*/GatewayPorts clientspecified/' /etc/ssh/sshd_config
        execute: service sshd reload
    Open the <SERVICE-PORT> on the firewall:
        execute: ufw allow <SERVICE-PORT> (e.g.: ufw allow 3193)


Jupyter notebook preparation:

    Start the server software ina jupyter notebook, identify the port it listens on (e.g.: 3193 from the email below, referenced as <SERVICE-PORT>)
    Open a terminal in the jupyter notebook
    Connect to the PTEP VM we prepared in the previous step:
        execute: ssh -R 0.0.0.0:<SERVICE-PORT>:localhost:<SERVICE-PORT> <PTEP-USERNAME>@<PTEP-VM-IP>
        (e.g.: ssh -R 0.0.0.0:3193:localhost:3193 bakcsa@172.16.0.13)


Connecting to the service:
Open a browser on your local machine and go to http(s)://<PTEP-VM-IP>:<SERVICE-PORT>/

http/https depends on the service running in the notebook. Most probably http.
```

**Comment by cl3mens22** [comment]
> Amazing and very extensive work! Well done 👍 I opened a pull request with some updates that I added while going through your notebook.
> 
> * see [Suggested changes cl3mens22/public-notebooks#1](https://github.com/cl3mens22/public-notebooks/pull/1)
> 
> Some of those changes were necessary to run the notebook. I was able to run almost everything. The only code that always crashed the kernel was the era5 cutting loop that has the `decision` bool. I rewrote it slightly to increase the speed by swapping the `for` loops around and reduce the amount of time calling `grps.select()`. But I still don't manage to run it completely. Though, I assume it is working with more CPU power, so I don't see a reason to change anything else here. Users can decide for themselves if they want to try or not. Did it run all well for you?
> 
> Have a look at the suggested changes and accept the pull request if you are happy with them. Then this pull request here will automatically be updated and we are ready to merge! Good job :-)

Hi, thanks a lot for the edits. I checked the era5 cutting loop, for me it works both ways on my local machine, the new version takes about 117 minutes, the old 187 minutes for one Lake ID. I will accept the pull request! Thanks a lot for the feedback!

**Comment by ykern** [comment]
Thank you for the confirmation that it works. I will now merge this into the main repo. Thanks a lot for your contribution! :+1:

**Pull request merged**
